# Generated by Django 4.2.2 on 2024-11-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_lesson_lesson_course'),
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('summ_payment', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма к оплате')),
                ('payment_method', models.CharField(choices=[('T', 'Оплата переводом'), ('C', 'Оплата наличностью')], default='T', max_length=1, verbose_name='Метод оплаты')),
                ('payment_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.course', verbose_name='Оплата курса')),
                ('payment_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.lesson', verbose_name='Оплата урока')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
