# Generated by Django 4.2.2 on 2024-11-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_lesson_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course_set', to='lms.course', verbose_name='Связь урока с курсом'),
        ),
    ]
